#!/usr/bin/env bash
# installs nginx web server
sudo apt-get -y update
sudo apt-get -y install nginx
echo "Holberton School" | sudo tee /var/www/html/index.nginx-debian.html
sudo sed -i "43i \trewrite ^/redirect_me$ https://reddit.com permanent;\n" /etc/nginx/sites-available/default
sudo service nginx start
