#!/usr/bin/env bash
# installs nginx web server
sudo apt-get -y update
sudo apt-get -y install nginx
echo "Holberton School" | sudo tee /var/www/html/index.nginx-debian.html
sudo sed -i "43i \\\tlocation /redirect_me {\n\t\t return 301 https://reddit.com;\n\t}\n" /etc/nginx/sites-available/default
sudo service nginx start
