#!/usr/bin/env bash
# installs nginx web server
sudo apt-get -y update
sudo apt-get -y install nginx
echo "Holberton School" | sudo tee /usr/share/nginx/html/index.html
sudo sed -i "30i \\\tlocation /redirect_me {\n\t\t return 301 https://www.reddit.com/;\n\t}\n" /etc/nginx/sites-available/default
sudo service nginx start
