#!/usr/bin/env bash
# installs nginx web server
sudo apt-get -y update
sudo apt-get -y install nginx
echo "Holberton School" | sudo tee /var/www/html/index.nginx-debian.html
sudo sed -i "30i \\\tlocation /redirect_me {\n\t\t return 301 https://www.reddit.com/;\n\t}\n" /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/custom_404.html
sudo sed -i "s@#error_page 404 /404.html;@error_page 404 /custom_404.html;\n\\tlocation = /custom_404.html {\n\t\t root /usr/share/nginx/html;\n\t\tinternal;\n\t}\n@" /etc/nginx/sites-available/default
sudo service nginx start
