#!/usr/bin/env bash
# install and configure haproxy
sudo apt-get update
sudo apt install -y haproxy
sudo sed -i "$ a \\\nfrontend hapnode\n\tbind *:80\n\tmode http\n\tdefault_backend backnodes\n\nbackend backnodes\n\tmode http\n\tbalance roundrobin\n\toption httpclose\n\toption forwardfor\n\tserver 1763-web-01 35.196.133.63:80 check\n\tserver 1763-web-02 54.163.27.112:80 check\n" /etc/haproxy/haproxy.cfg
sudo service haproxy start
