#!/usr/bin/env bash
# Displays Holberton School unless it is bad luck
x=0
while [ $x -lt 10 ]
do
    if [ $x -eq 3 ]
    then
	echo "bad luck"
    elif [ $x -eq 7 ]
    then
	echo "good luck"
    else
	echo "Holberton School"
    fi
    ((x++))
done
