#!/usr/bin/env bash
# Displays 1 to 20 and tells when it is bad luck
x=1
while [ $x -le 20 ]
do
    echo "$x"
    case "$x" in
	4) echo "bad luck from China" ;;
	9) echo "bad luck from Japan" ;;
	17) echo "bad luck from Italy" ;;
    esac
    ((x++))
done
